spring:
  profiles:
    active: dev
  application:
    name: notification-service
  config:
    import: "configserver:http://localhost:8888"
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    

