spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123qwe
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    template:
      observation-enabled: true
    listener:
      simple:
        observation-enabled: true
      direct:
        observation-enabled: true


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, tracing, refresh

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

otel:
  exporter:
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans
  resource:
    attributes:
      service.name: ${spring.application.name}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] %-5level %logger{36} - %msg%n"
  level:
    com.sesac: DEBUG
    io.micrometer.tracing: DEBUG
    org.springframework.web: DEBUG


order:
  event:
    exchange: order.exchange
    queue:
      notification: order.notification.queue
      inventory: order.inventory.queue
      payment-request: order.payment.request.queue
      inventory-failed: order.inventory.failed.queue
      payment-failed-inventory-restore: order.inventory.payment.failed.queue
      payment-failed-order-cancel: order.payment.failed.queue
      payment-completed-order-completed: order.payment.completed.queue

    routing-key:
      notification: order.notification
      inventory: order.inventory
      payment-request: order.payment.request
      inventory-failed: order.inventory.failed
      payment-failed-inventory-restore: order.inventory.payment.failed
      payment-failed-order-cancel: order.payment.failed
      payment-completed-order-completed: order.payment.completed


info:
  environment: "Development"
  debug: true

